
tasks:
  unit-test:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
        ls -a 
        ls target
        scp -r target/ ubuntu@:/opt/apache-tomcat-8.5.81/webapps
