tasks:
  unit-job:
    #runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package                  # build the package 
        ls -a
        ls target 
    - docker/build:
        image: razoropsrepocode/spring       # build the image with Dockerfile
        push: true                                 # push image to docker hub repository Which is integrated  
        tags: ["latest-v2"]
        ## kubernets deployment
  deploy-job:
    steps:
    - checkout
    - commands:
      - |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl get svc
